---
- hosts: deploy
  #become: True
  tasks:
    - name: Install python pip
      yum: 
        name: python-pip
        state: present
    - name: Install Docker
      yum:
        name: docker
        state: present
    - name: start Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: AWS CLI
      yum:
        name: awscli
        state: present
    - name: Install git
      yum:
        name: git
        state: present
    - name: Establish a login to ECR
      shell: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 174392322073.dkr.ecr.ap-south-1.amazonaws.com
    - name: Pull the image from ECR to CD server
      shell: docker pull 174392322073.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:18
    - name: Run the container using the docker image
      shell: docker run --name=javaapp-container -p 8085:8080 --detach 174392322073.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr:18
        
        
